# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the
# server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# these are site variables used by the theme
theme: minima
#theme: jekyll-theme-slate
#theme: jekyll-theme-midnight
#theme: jekyll-swiss
#theme: jekyll-seo-tag
#
#theme: jekyll-theme-primer
#theme: hacker
#title: donmcg project site
title: fairhillbillies
#description: A static site hosted on GitHub Pages.
# Successful and
# unsuccessful efforts. 
#description: >- # this means to ignore newlines until next key:
#description: # \n is ignored ...
#  "The happiest of all lives is a busy solitude\n - Voltaire"
#description: | # block format
#  The happiest of all lives is a busy solitude
#  - Voltaire
description: # \n is ignored ...
  'The happiest of all lives is a busy solitude. Voltaire'
url: "https://donmcg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
#github_username:  gun_donmcg
github_username:  donmcg
email: your-email@example.com
author:  author_donmcg

#author:  'Errabundi Saepe, Semper Certi'
#email: '(Often wrong, but always certain.)'

# other settings 
name: name_donmcg
owner: owner_donmcg

# prevent default head.html (minima) from loading google.analytics
environment: development

# experimental use of kramdown
markdown: kramdown

# for LaTex
# this stuff is not needed.  see _includes/head.html
#markdown: kramdown
#highlighter: rouge
#kramdown:
#  math_engine: mathjax
#   <script type="text/javascript" async
#     src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
#   </script>



# note there is only one paginate_path. 
# this means that paginate only works for one set of posts
#paginate_path: "/fizzbin/page:num"
paginate_path: "/blog/page:num"
paginate: 5

# Build settings
#theme: hacker-blog
plugins:
#  - jekyll-remote-theme
#  - jekyll-feed
  - jekyll-paginate

# header_pages controls the order and allows for deep path names
header_pages:
  - index.html
  - about.md
  - blog/index.html # special case for paginator
#  - library/mini_topical.html
#  - fizzbin/index.html
#  - library/veggie_topical.html
#  - meat.html
#  - plant.html
#  - rock.html

# collections provides post content by context
# paginate will not work for any of these; use site instead
collections:
  music:
    output: true
  mini:
    output: true
#    permalink: /:path/ # flattens the contents of _mini/ directly under _site
#    permalink: /mini/:path/ # mini/xyz.md becomes mini/xyz/index.html
#    permalink: /mini/ # mini/*.md becomes mini/index.html (one file)
# mini/blog:
#   output: true
# animal:
#   output: true
# vegetable:
#   output: true
# mineral:
#   output: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - trash/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
